# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Surender Lohia
tag_text: Surender Lohia
email: surender.lohia.e@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Surender Lohia | Front-End Developer, Passionate programmer.
baseurl: "" # the subpath of your site, e.g. /blog
url: "www.surender.net" # the base hostname & protocol for your site
twitter_username: surender_lohia
github_username:  surenderlohia
logo: /assets/img/surender.jpg

# Build settings
markdown: kramdown

exclude: ["_app",
          "Gemfile",
          "Gemfile.lock",
          "Gulpfile.js",
          "assets/js/bundle.js.map",
          "assets/js/main.js",
          "node_modules",
          "package.json"]
